export const SET_THEATER_SCHEDULE = 'SET_THEATER_SCHEDULE';
export const SET_INIT_LOADING_STATUS = 'SET_INIT_LOADING_STATUS';
export const SET_SELECTED_PERFORMANCE_ID = 'SET_PERFORMANCE_ID';
export const SET_WIZARD_STEP = 'SET_WIZARD_STEP';
export const INCREASE_STEP_IDX = 'INCREASE_STEP_IDX';
export const DECREASE_STEP_IDX = 'DECREASE_STEP_IDX';
