export const SET_THEATER_SCHEDULE = 'SET_THEATER_SCHEDULE';
export const SET_INIT_LOADING_STATUS = 'SET_INIT_LOADING_STATUS';
export const SET_SELECTED_PERFORMANCE_ID = 'SET_PERFORMANCE_ID';
export const SET_WIZARD_STEP = 'SET_WIZARD_STEP';
export const SET_PAYMENT_TYPE = 'SET_PAYMENT_TYPE';
export const SET_DEDICATED_FORM_FIELD = 'SET_DEDICATED_FORM_FIELD';
export const RESET_STATE = 'RESET_STATE';
